.PHONY: build test test-acceptance test-examples

build:
	go fmt ./...
	go mod tidy
	go build ./...

test:
	go vet ./...
	staticcheck ./...
	go test ./...

test-acceptance:
	go test -v -tags=acceptance ./tests/acceptance/...

test-examples:
	go test -v -tags=examples ./tests/examples/...
